format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncation_length = 20
truncation_symbol = "…/"

[cmd_duration]
format = "[$duration]($style)"

[git_status]
untracked = "[?$count](yellow)"
staged = "[+$count](green)"
modified = "[!$count](purple bold)"
deleted = "[✘$count](red bold)"
renamed = "[»$count](cyan)"
stashed = "[\\$$count](purple)"
ahead = "[⇡$count](green)"
diverged = "[⇕⇡$ahead_count⇣$behind_count](red bold)"
behind = "[⇣$count](purple)"

[git_commit]
# tag_disabled = false
