prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "package",
    "cmd_duration",
    "line_break",
    "character",
]

[directory]
truncation_length = 20

[cmd_duration]
prefix = ""

[git_status]
untracked.style = "yellow"
untracked_count.enabled = true
untracked_count.style = "yellow"
staged.value = "+"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
modified = "*"
modified_count.enabled = true
