format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncation_length = 20

[cmd_duration]
format = "[$duration]($style)"

[git_status]
untracked.style = "yellow"
untracked_count.enabled = true
untracked_count.style = "yellow"
staged.value = "+"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
modified.value = "*"
modified.style = "purple"
modified_count.enabled = true
modified_count.style = "purple"
deleted_count.enabled = true
show_sync_count.enabled = true
renamed.style = "blue"
renamed_count.enabled = true
renamed_count.style = "blue"
