#! /usr/bin/env zsh
# zmodload zsh/zprof

autoload -Uz compinit

zmodload -i zsh/complist

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.local/cache"
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_STATE_HOME="$HOME/.local/state"

export DOTFILE="$HOME/.bashrc.d"
export SUB_MODULES="$DOTFILE/submodules"

# wsl | linux | darwin -- a module can add a <module>/$SYSTEM.zsh next to its init.zsh
if [[ -n "$WSL_DISTRO_NAME" ]]; then
  export SYSTEM="wsl"
else
  export SYSTEM="${OSTYPE%%[0-9.-]*}"
fi
export SYSFILE="$DOTFILE/system/$SYSTEM"

export LANG=fr_FR.UTF-8
export EDITOR="nvim"
export VISUAL="nvim"
export MANPAGER="nvim +Man!"
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=magenta,fg=white,bold'
# export TERM='tmux-256color-italic'

export HISTFILE=~/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000

# prevent the global variable PATH to have duplicate
typeset -U path
path=(
  "$XDG_BIN_HOME"
  "$DOTFILE/bin"
  "$HOME/bin"
  $path
)

autoload -Uz "$DOTFILE/function.d/load_func"

# load all core function
load_func "core"

module "zsh"

# Rebuild the completion dump (full `compinit`, which re-verifies fpath) when
# it is stale or was generated by a different zsh version; otherwise load the
# cached dump fast with `compinit -C`, which skips those checks.
#
# The version guard is what heals a zsh upgrade: after an update the dump still
# carries the old "version: X.Y.Z" stamp, so the next shell (or `source`)
# rebuilds it instead of trusting a stale cache -- which is what caused the
# `comparguments: command not found` errors on tab completion.
#
# Glob qualifier notes for the staleness test:
# - '#q' is an explicit glob qualifier that makes globbing work within zsh's [[ ]] construct.
# - 'N' makes the glob pattern evaluate to nothing when it doesn't match (rather than throw a globbing error)
# - '.' matches "regular files"
# - 'mh+24' matches files (or directories or whatever) that are older than 24 hours.
#
# The dump is removed first: `compinit` leaves an unchanged dump untouched, so its
# mtime would stay old and every shell would pay the full rebuild.
if [[ -n ${HOME}/.zcompdump(#qN.mh+24) ]] \
  || ! grep -q "version: ${ZSH_VERSION}\$" "${HOME}/.zcompdump" 2>/dev/null; then
  rm -f "${HOME}/.zcompdump"
  compinit
else
  compinit -C
fi

# uncomment to know what take to much time at the load and init time
# Don't forget to uncomment the 'import' at the top of the file
# zprof
