set term=screen-256color
set shell=/bin/sh

if has('nvim')
    let s:editor_root=expand("~/.nvim")
else
    let s:editor_root=expand("~/.vim")
endif

let g:python_host_prog='/usr/bin/python'

let mapleader = '='

"" start  vundle confguration {{{

set nocompatible
filetype off

let &rtp = &rtp . ',' . s:editor_root . '/bundle/Vundle.vim'
call vundle#rc(s:editor_root . "/bundle")

" Plugin Start {{{
" source the plugin list
Plugin 'gmarik/Vundle.vim'                   " vundle plugin

" begin   plugin
" " do not uninstall -> dependency

" " functionalities plugin
Plugin 'kien/ctrlp.vim'                      " fuzzy file finder
Plugin 'vim-scripts/Gundo'                   " better undo/redo
Plugin 'myusuf3/numbers.vim'                 " better line numbers
Plugin 'tpope/vim-surround'                  " some function for surrounding text
Plugin 'scrooloose/nerdcommenter'            " better comment function
Plugin 'Xuyuanp/nerdtree-git-plugin'         " git in neerdtree
Plugin 'scrooloose/nerdtree'                 " tree view
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'godlygeek/tabular'                  " easy align

" " git integration
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-git'
Plugin 'junegunn/gv.vim'
Plugin 'airblade/vim-gitgutter'              " git integration

" " UI plugin
Plugin 'vim-airline/vim-airline'             " better status line
Plugin 'vim-airline/vim-airline-themes'      " more themes for airline
Plugin 'ap/vim-buftabline'
" Plugin 'bling/vim-bufferline'
Plugin 'tabman.vim'                          " show a panel with all tabs and each panel in them
Plugin 'zhaocai/GoldenView.Vim'              " better panel manager
Plugin 'ntpeters/vim-better-whitespace'      " show space at end of line

" " syntax and completion
Plugin 'Valloric/YouCompleteMe'
Plugin 'scrooloose/syntastic'                " syntax checker

" " htlm
Plugin 'mattn/emmet-vim'                     " emmet plugin for html
Plugin 'othree/html5.vim'

" " markdown
Plugin 'plasticboy/vim-markdown'             " markdown support
Plugin 'cespare/vim-toml'
Plugin 'elzr/vim-json'

" " python
Plugin 'davidhalter/jedi-vim'                " python auto-completion

" " rust
Plugin 'racer-rust/vim-racer'                " plugin for rust completion
Plugin 'rust-lang/rust.vim'                  " plugin for rust syntax

" " scala
Plugin 'derekwyatt/vim-scala'
Plugin 'gre/play2vim'                        " support of scala-play framwork for vim
Plugin 'ensime/ensime-vim'

" " js family
Plugin 'moll/vim-node'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'leafgarland/typescript-vim'          " typescript
Plugin 'Quramy/tsuquyomi'                    " completion typescript
Plugin 'Quramy/vim-js-pretty-template'       " templat string es6+

" Plugin 'Shutnik/jshint2.vim'                 " JSHint2
"

filetype plugin indent on
" end    vundle configutation
" }}}
" Plugin end

set omnifunc=syntaxcomplete#Complete

"" load all config file
runtime! config/**/*.vim
