[v1]
"alacritty 0.1.0 (git+https://github.com/jwilm/alacritty#4d4e62db92c6ad5647d6d5701b1c3f97dfe645c5)" = ["alacritty"]
"bat 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 8.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"cargo-web 0.6.26 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-web"]
"choose 1.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["choose"]
"diesel_cli 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"gli 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gli"]
"racer 2.1.48 (registry+https://github.com/rust-lang/crates.io-index)" = ["racer"]
"rhc 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rhc"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rusty-tags 3.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-tags"]
"yj 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["yj"]
