#! /bin/sh
# vim:ft=zsh

function root() {
  local ref
  ref=$(command git rev-parse --show-toplevel --quiet)
  local ret=$?

  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return # no git repo
  fi
  echo $ref
}

root
